### ISSUE TITLE
ERROR  Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3472]
On the print pod in production there is the following log line 3 times:
```
 ERROR  Navigation timeout of 30000 ms exceeded

  at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:162:12)
  at async Frame.goto (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:207:21)
  at async CDPPage.goto (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:438:16)
  at async server-middleware/routes/pdfGeneratorNativeChrome.js:97:5

(took 10387581 millisecons / using 91.797464MB)
```

- [ ] Check if large pdf (or a slow api) lead to a timeout while rendering the pdf
- [ ] Fix it by either reducing the time to render the pdf or increase the timeout

**Comment by carlobeltrame** [comment]
This has happened a few times since we increased the timeout and started tracking it in sentry.

**Comment by BacLuc** [comment]
This did not happen anymore since #3478
and since the large camp with over 170 activities in summer 2023 is over.
