### ISSUE TITLE
ERROR  Navigation failed because browser has disconnected!

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3473]
We have this error some times in the print pod on production.
@BacLuc guesses that this is user leaving the print page while a print is running.
```
 ERROR  Navigation failed because browser has disconnected!

  at new LifecycleWatcher (node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:83:223)
  at Frame.goto (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:206:25)
  at CDPPage.goto (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:438:91)
  at server-middleware/routes/pdfGeneratorNativeChrome.js:97:16
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

- [ ] Check if this is a problem
- [ ] Add a catch for this error that it does not end up in sentry if it is not a problem

**Comment by carlobeltrame** [comment]
This has only happened on staging (and a feature branch deployment) since we started keeping track of it in sentry.

**Comment by BacLuc** [comment]
This did not happen anymore since #3478
and since the large camp with over 170 activities in summer 2023 is over.
