### ISSUE TITLE
ERROR  Protocol error (Page.printToPDF): Target closed

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3474]
We have this error in the print pod on production
```
 ERROR  Protocol error (Page.printToPDF): Target closed

  at new Callback (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:61:35)
  at CallbackRegistry.create (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:106:26)
  at Connection._rawSend (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:26)
  at CDPSessionImpl.send (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:425:78)
  at CDPPage.createPDFStream (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:723:88)
  at CDPPage.pdf (node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:749:37)
  at server-middleware/routes/pdfGeneratorNativeChrome.js:103:28
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
@BacLuc guesses that the problem is similar to #3473 

- [ ] Check if this is a problem
- [ ] Add a catch for this error that it does not end up in sentry if it is not a problem

**Comment by carlobeltrame** [comment]
This has only happened on staging since we track it in sentry.

**Comment by BacLuc** [comment]
This did not happen anymore since #3478
and since the large camp with over 170 activities in summer 2023 is over.
