### ISSUE TITLE
Tests für Form Komponenten komplettieren

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#412]
To do E-Fields:
- [x] ETextField
- [x] ECheckbox
- [x] ESelect
- [x] ESwitch
- [x] ETextArea
- [x] ERichText
...

To do API fields:
- [x] ApiWrapper
- [x] ApiTextField
- [x] ApiSelect
- [x] ApiCheckbox
- [x] ApiColorPicker
- [x] ApiDatePicker
- [x] ApiSwitch
- [x] ApiTextarea #2375
- [x] ApiTextfield
- [x] ApiRichText #2374
- [x] ApiTimePicker

To do in ApiWrapper:
- [x] `relation` prop, see https://github.com/ecamp/ecamp3/pull/645#discussion_r526205492
Implemented with #1122 

Currently not in scope (siehe #637):
- DatePicker
- TimePicker
- ColorPicker

**Comment by BacLuc** [comment]
Beim ApiTextArea bin ich über folgendes Problem gestolpert:
Wenn ich den TipTapEditor mounten wollte, kam folgender fehler (siehe unten).
Da ich mit ShallowMount nur noch den ApiWrapper testen würde, habe ich diesen test weggelassen.

```
node_modules/vue/dist/vue.runtime.common.dev.js:621
    [Vue warn]: Error in callback for watcher "value": "RangeError: Maximum call stack size exceeded"
    
    found in
    
    ---> <TiptapEditor>
           <VTiptapEditor>
             <ValidationProvider>
               <ETextarea>
                 <VForm>
                   <ValidationObserver>
                     <ApiWrapper>
                       <ApiTextarea>
                         <App>
                           <Root>
  
console.error
 
node_modules/vue/dist/vue.runtime.common.dev.js:1884
    RangeError: Maximum call stack size exceeded
        at Window.get document [as document] (/home/lucius/projects/ecamp/ecamp3/frontend/node_modules/jsdom/lib/jsdom/browser/Window.js:217:7)
        at Document.Object.getPrototypeOf.getSelection (/home/lucius/projects/ecamp/ecamp3/frontend/node_modules/prosemirror-view/src/index.js:259:77)
        at Document.Object.getPrototypeOf.getSelection (/home/lucius/projects/ecamp/ecamp3/frontend/node_modules/prosemirror-view/src/index.js:259:95)
        at Document.Object.getPrototypeOf.getSelection (/home/lucius/projects/ecamp/ecamp3/frontend/node_modules/prosemirror-view/src/index.js:259:95)
        at Document.Object.getPrototypeOf.getSelection (/home/lucius/projects/ecamp/ecamp3/frontend/node_modules/prosemirror-view/src/index.js:259:95)
```

**Comment by carlobeltrame** [comment]
Es ist möglich, beim mounten einzelne Subkomponenten zu mocken. Ob das in diesem Fall Sinn macht bin ich aber nicht sicher.
