### ISSUE TITLE
Picasso: Only show small edit button when hovering over scheduleEntry

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#678]
https://github.com/ecamp/ecamp3/pull/656#discussion_r526354065

**Comment by blackpandan** [comment]
can you assign this to me

**Comment by carlobeltrame** [comment]
@blackpandan are you still working on this? Do you need help with it?

**Comment by DeNic0la** [comment]
Can someone assign me

**Comment by pmattmann** [comment]
I'm not sure if this is still necessary. The picasso now has an edit-mode.
In the display-mode the edit-butten is already hidden.

check it out.

**Comment by DeNic0la** [comment]
I think you are right, I am unable to check since I have some issues with the `docker-compose up` thing. 
I followed the installation instructions and I am not sure what went wrong, could someone point me in the right direction?

Docker version 20.10.11, build dea9396e18
Ubuntu 20.04.3 LTS

Console:
```
Step 46/46 : COPY docker/caddy/Caddyfile /etc/caddy/Caddyfile
 ---> cbddb324e665
Successfully built cbddb324e665
Successfully tagged ecamp3_caddy:latest
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 664, in up
  File "compose/service.py", line 364, in ensure_image_exists
  File "compose/service.py", line 1133, in build
  File "compose/service.py", line 1948, in build
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpa_uoqxhy'
[52539] Failed to execute script docker-compose
```

**Comment by DeNic0la** [comment]
> I'm not sure if this is still necessary. The picasso now has an edit-mode. In the display-mode the edit-butten is already hidden.

You are correct. I assume this is done then.
